services:
  backend:
    restart: unless-stopped
    environment:
      - ENV=prod
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
    networks: [ web, internal ]

  frontend:
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://api.${DOMAIN}
    networks: [ web, internal ]

  redis:
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks: [ internal ]

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks: [ web, internal ]
    depends_on:
      - backend
      - frontend

networks:
  web:
  internal:

volumes:
  caddy-data:
  caddy-config:
  redis-data:
